### ISSUE TITLE
Requirements - Scoreboard

### ISSUE THREAD

**Issue by devrimy7** [LeonUwe/IAV_Distortion#19]
Relates to #7 

In the following file you can see all the requirements for the scoreboard. These requirements relate to the product and quality characteristics according to ISO 25010:2023

[Requirements_Scoreboard.pdf](https://github.com/user-attachments/files/17586647/Requirements_Scoreboard.pdf)

**Comment by devrimy7** [comment]
Bitte einmal reviewen wenn ihr Zeit habt, dann würde ich bei den anderen Sachen genauso vorgehen.

**Comment by LeonUwe** [comment]
I think these are reasonable requirements and a good guideline for the developers.

However they should be in English to keep consistency with the rest of the project as they might be kept as part of the documentation.

**Comment by devrimy7** [comment]
done
