### ISSUE TITLE
Requirements - Proximity Timer

### ISSUE THREAD

**Issue by devrimy7** [LeonUwe/IAV_Distortion#20]
Relates to #8 

In the following file you can see all the requirements for the proximity timer. These requirements relate to the product and quality characteristics according to ISO 25010:2023

[Requirements_Proximity-Timer.pdf](https://github.com/user-attachments/files/17644582/Requirements_Proximity-Timer.pdf)

**Comment by LeonUwe** [comment]
4. Adaptability

I don't understand how the timer would need to adapt to different tracks. The current implementation uses simple x,y-coordinates of the cars. The track layout makes no difference for the timer.

**Comment by LeonUwe** [comment]
5. Fault Tolerance

Conversation with @Einfachmario45 has resulted in the decision, that this requirement will not be specifically fulfilled. The required effort is not worth the time compared to the resulting gain.

**Comment by devrimy7** [comment]
uploaded new requirements
