### ISSUE TITLE
@everyone Setup on PC

### ISSUE THREAD

**Issue by LeonUwe** [LeonUwe/IAV_Distortion#3]
Please set up the project on your PC and start familiarising yourself with the codestructure.

Everyone should have a rough understanding of the project and be able to set it up and run it.

The people in this project with roles of the more organizational type have agreed to help the developers when necessary.
Not having the project setup already, and therefore not being familiar with it, creates unnecessary overhead, when additional manpower is needed.

Please react to this issue with a comment or otherwise to signal that you have successfully started the project on your PC and have driven a virtual car via your smartphone.

**Comment by githubgedoens** [comment]
Funktioniert

**Comment by devrimy7** [comment]
Funktioniert nicht ganz, wäre cool wenn wer helfen könnte die Tage

**Comment by Einfachmario45** [comment]
funktioniert

**Comment by LeonUwe** [comment]
@devrimy7 Eine Ahnung woran es liegen könnte?

**Comment by devrimy7** [comment]
funktioniert

**Comment by SinanBaykalBS** [comment]
funktioniert

**Comment by LeonUwe** [comment]
Setup has worked for everyone.
