### ISSUE TITLE
Requirements - Switch between virtual cars

### ISSUE THREAD

**Issue by devrimy7** [LeonUwe/IAV_Distortion#34]
Relates to [#32 ](https://github.com/users/LeonUwe/projects/1/views/1?pane=issue&itemId=84650281&issue=LeonUwe%7CIAV_Distortion%7C5)

In the following file you can see all the requirements for the switch between virtual cars. These requirements relate to the product and quality characteristics according to ISO 25010:2023

[Requirements_Switch-virtual-Cars.pdf](https://github.com/user-attachments/files/17645069/Requirements_Switch-virtual-Cars.pdf)

**Comment by githubgedoens** [comment]
Very good and useful requirements. But I'm not sure, how realistic the faul tolerance requirement is

**Comment by devrimy7** [comment]
Thought this could be useful so there is no interruption and the race stays fluent

**Comment by githubgedoens** [comment]
> Thought this could be useful so there is no interruption and the race stays fluent

I see your point and after further thinkig about it, this could prove very helpful for when the minigames are implemented.
