### ISSUE TITLE
Requirements - Bot controlled cars

### ISSUE THREAD

**Issue by devrimy7** [LeonUwe/IAV_Distortion#35]
Relates to [#6 ](https://github.com/users/LeonUwe/projects/1/views/1?pane=issue&itemId=84650282&issue=LeonUwe%7CIAV_Distortion%7C6)

In the following file you can see all the requirements for the bot controlled cars. These requirements relate to the product and quality characteristics according to ISO 25010:2023

[Requirements - Bot controlled cars.pdf](https://github.com/user-attachments/files/17678950/Requirements.-.Bot.controlled.cars.pdf)

**Comment by LeonUwe** [comment]
@Einfachmario45 Do you have any other thoughts on the requirements?
