### ISSUE TITLE
Bug: Tests dont pass anymore

### ISSUE THREAD

**Issue by Max9786** [LeonUwe/IAV_Distortion#59]
Tests in EnvironmentManager_Test and DriverUI_Test dont pass anymore and throw different errors (after taking over the iav dev version)

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Update EnvironmentManager and DriverUI classes to resolve test failures. Modify test cases to accommodate changes in the implementation.

You can review changes in this commit: https://github.com/lkilu6456546/LeonUwe-IAV_Distortion-59/commit/ecd7f3fdb139c011333f9af7407654527214b1ee.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
